---
all:
  hosts:
    local:
      ansible_ssh_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"

      nas__path:
        # root: '/srv/nas'
        samba: '/srv/nas/samba'
        docker: '/srv/nas/docker'
        nfs: '/srv/nas/nfs'
