---
- name: Provision Python
  hosts: all
  gather_facts: no
  tasks:
    - name: Boostrap python
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

- name: Provision
  hosts: all
  vars:
    req_apt:
      - 'vim'
      - 'tmux'
      - 'python3-wheel'

  tasks:
    - name: Update apt-cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: result
      until: result is succeeded

    - name: Install some packages
      apt:
        name: ""
        state: present
      register: result
      until: result is succeeded

    - name: Create user
      user:
        name: user
        state: present
        update_password: on_create
        group: user
        shell: /bin/bash

    - name: Create workdir
      file:
        path: /data
        state: directory
        owner: root
        group: root
        mode: 0755

- name: Container cleanup
  hosts: all
  gather_facts: no
  tasks:
    - name: Clean-up
      command: >
        apt-get autoremove -y && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
