---
- name: "ngenetzky-nas v0.1.0 - ngenetzky uses ansible-nas"
  hosts: all
  vars_files:
  - build/ngenetzky-ansible-vault-vars.yml
  tasks: []
  roles:

  - role: bertvv.samba
    tags:
      - samba
      - skip_ansible_lint

  - role: geerlingguy.docker
    tags:
      - docker
      - skip_ansible_lint
    vars:
      docker_users:
      - "{{ ansible_nas_user }}"

  - role: geerlingguy.nfs
    tags:
      - nfs
      - skip_ansible_lint

  - role: davestephens.nas
