---
- hosts: dev
  become: yes
  pre_tasks:
  - name: Update apt cache
    apt: update_cache=yes
  tasks:
  # - import_tasks: ../../tasks/desktop-kde.yml
  - import_tasks: ../../tasks/desktop-developer.yml
  - import_tasks: ../../tasks/shell-base.yml
  - import_tasks: ../../tasks/desktop-mplab.yml
