Vagrant.configure("2") do |config|

  config.vm.provider "libvirt" do |v|
      v.memory = 1024
      v.cpus = 2
  end
  
  config.vm.define "ansible", autostart: "True" do |ansible|
      ansible.vm.box = "generic/ubuntu1804"
      ansible.vm.hostname = "ansible-play-ngenetzky-nas"

      ansible.vm.provision "shell", inline: "sudo yum -y install epel-release && sudo yum -y install git vim python-pip"
      ansible.vm.provision "shell", inline: "sudo pip install ansible"
      ansible.vm.provision "file", source: ".", destination: "/tmp/ansible-play"
      ansible.vm.provision "shell", inline: "(cd /tmp/ansible-play && [ -f roles/requirements.yml ] && ansible-galaxy install -r roles/requirements.yml) || echo 'No requirements file found, skipping Galaxy installs...'"
      ansible.vm.provision "shell", inline: "(cd /tmp/ansible-play && ansible-playbook -v -i inventory/test playbook.yml)"
  end
end
