---
- name: Bootstrap ansible
  hosts: all
  gather_facts: false
  become: true

  roles:
    - robertdebock.bootstrap

  tasks:
    - name: test connection
      ping:
- name: User setup
  hosts: all
  # become: true

  roles:
    - ngenetzky.editor-vim
