# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.ssh.username = "user"
    # config.ssh.private_key_path  = ''

    config.vm.provider "docker" do |d|
        d.build_dir = '.' # build from provided Dockerfile
        #d.image = image  # use the predefined image
        d.remains_running = true
        d.cmd = ["/usr/sbin/sshd", "-D"]
        d.has_ssh = true
    end
end
