- import_tasks: symlinks.yml
- import_tasks: public_git_repos.yml

- name: Download public ssh keys
  get_url:
    url: https://github.com/NGenetzky.keys
    dest: "{{ dotfiles_dest }}/.ssh/github.com.ngenetzky.keys"
    checksum: "{{ dotfiles__ssh_pub_gh_checksum }}"

- name: Create tar archive on the Ansible controller
  # The > is a folding block operator. That is, it joins multiple lines together by spaces.
  command: >
    tar --create --gzip
    {{ "" if (dotfiles__include_vcs|bool) else "--exclude-vcs" }}
    --file "{{ dotfiles__temp_tar_file }}"
    --directory "{{ dotfiles_dest }}" .
  args:
    warn: False
    creates: '{{ dotfiles__temp_tar_file }}'
  become: False
  delegate_to: 'localhost'
  run_once: True
