# TODO: it would be nice to lock down the versions.
- name: Clone src repositories from github
  git:
    repo: "https://github.com/{{ item.src }}"
    dest: "{{ dotfiles_dest }}/{{ item.dst }}/"
  with_items:
    - { src: "tmux-plugins/tpm.git", dst: ".tmux/plugins/tpm" }
    - { src: "gmarik/vundle.git", dst: ".vim/bundle/vundle" }
    - { src: "junegunn/vim-plug.git", dst: ".vim/bundle/vim-plug" }
    - { src: "spf13/spf13-vim.git", dst: ".vim/spf13-vim" }
    - { src: "Bash-it/bash-it.git", dst: ".bash_it" }

- name: Clone src repositories from github at specific version
  git:
    repo: "https://github.com/{{ item.src }}"
    dest: "{{ dotfiles_dest }}/{{ item.dst }}/"
    version: "{{ item.version | d(omit) }}"
  with_items:
    - { src: "TheLocehiliosan/yadm.git", dst: ".local/src/yadm",  }
    - { src: "ngenetzky/home.git", dst: ".local/src/home", version: "live/virt-nateg-u18"}
    - { src: "ohmybash/ohmybash.git", dst: ".oh-my-bash", version: "89e505415284619377df9d8dc73f033572e24621"}
    - { src: "ohmyzsh/ohmyzsh.git", dst: ".oh-my-zsh", version: "452586e79a06d568a3445b26e6d6f4d62c111f52"}
