# TODO: it would be nice to lock down the versions.
- name: Clone src repositories from github
  git:
    repo: "https://github.com/{{ item.src }}"
    dest: "{{ dotfiles_dest }}/{{ item.dst }}/"
  with_items:
    - { src: "tmux-plugins/tpm.git", dst: ".tmux/plugins/tpm" }
    - { src: "gmarik/vundle.git", dst: ".vim/bundle/vundle" }
    - { src: "junegunn/vim-plug.git", dst: ".vim/bundle/vim-plug" }
    - { src: "spf13/spf13-vim.git", dst: ".vim/spf13-vim" }
    - { src: "Bash-it/bash-it.git", dst: ".bash_it" }
