---
- hosts: default
  become: yes
  pre_tasks:
  - name: Update apt cache
    apt: update_cache=yes
  tasks:
  - import_tasks: ../../tasks/shell-base.yml

  roles:
  - role: robertdebock.buildtools
  - role: geerlingguy.pip
    pip_install_packages: []
    pip_package: python-pip
  - role: geerlingguy.nodejs
    nodejs_version: "10.x"
    nodejs_npm_global_packages: []

  - role: geerlingguy.ansible
    ansible_install_method: pip
    ansible_install_version_pip: "2.7.0"
  - role: geerlingguy.docker
    docker_users: ['ngenetzky'] # TODO: avoid hardcoding
  - role: robertdebock.openssh
  - role: geerlingguy.git
  # - role: geerlingguy.samba
  # - role: geerlingguy.nfs
  # - role: robertdebock.go
