---
- name: Has Directory (~/git/ngenetzky)
  file:
    path: "~/git/ngenetzky/"
    state: directory
    recurse: yes
- name: Download public ssh keys
  get_url:
    url: https://github.com/NGenetzky.keys
    dest: ~/git/ngenetzky/.github.ngenetzky.keys
    checksum: md5:e5273998bb40b6aedee9bccfb6e5b7f4.
- name: Clone or update all repositories
  git:
    repo: ssh://git@github.com/NGenetzky/{{ item }}.git
    dest: "~/git/ngenetzky/{{ item }}"
  with_items:
    # - dev-shell
    # - docker-data-crow
    # - documents
    # - dotvim
    # - git-annex-adapter
    # - meta-genet
    # - particle-projects
    - ansible-role-editor-vim
    - dotfiles
    - dotfiles-holman
    - dotphiles
    - hugo-academic-kickstart
    - hugo-resume
    - iac
    - jatdb
    - meta-ngenetzky
    - shlib
