version: '3'
services:
  main:
    # user: user # phusion must run as root
    command: ['sleep', 'infinity']
    # environment:
    # - "HOME=/home/user/"
    build: ./
    # volumes:
    # - ./:/workspace

    # Forwards the host Docker socket to the container.
    # - /var/run/docker.sock:/var/run/docker.sock
