
# -*- mode: ruby -*-
# vi set ft=ruby:

# Vagranfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.define "phusion" do |v|
    v.vm.provider "docker" do |d|
      d.cmd   = ["sleep", "infinity"]
      d.build_dir = "./"
      d.has_ssh = true
      d.vagrant_vagrantfile = "./Vagrantfile"
    end
  v.ssh.username = "user"
  v.ssh.private_key_path = "phusion.key"
  v.ssh.port = "22"
  # v.vm.provision "shell", inline: "echo Hello"
  # v.vm.synced_folder "./", "/vagrant"
 end
end
