---
- name: "ngenetzky-nas v0.1.0 - portainer up"
  hosts: all
  # tasks: []
  vars:
    ansible_nas_domain: novo.genetzky.us
    portainer_available_externally: "true"
  roles:
  - role: nas_portainer